### ISSUE TITLE
using the staticfiles app without having set the STATIC_ROOT setting to a filesystem path

### ISSUE THREAD

**Issue by hseritt** [hseritt/dockerize#4]
Seeing this issue on startup:

```
web_1  |   Applying sessions.0001_initial... OK
web_1  | Superuser created successfully.
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/src/myproject/manage.py", line 22, in <module>
web_1  |     main()
web_1  |   File "/usr/src/myproject/manage.py", line 18, in main
web_1  |     execute_from_command_line(sys.argv)
web_1  |   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
web_1  |     utility.execute()
web_1  |   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
web_1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
web_1  |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
web_1  |     self.execute(*args, **cmd_options)
web_1  |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
web_1  |     output = self.handle(*args, **options)
web_1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web_1  |   File "/usr/local/lib/python3.11/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 209, in handle
web_1  |     collected = self.collect()
web_1  |                 ^^^^^^^^^^^^^^
web_1  |   File "/usr/local/lib/python3.11/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 135, in collect
web_1  |     handler(path, prefixed_path, storage)
web_1  |   File "/usr/local/lib/python3.11/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 368, in copy_file
web_1  |     if not self.delete_file(path, prefixed_path, source_storage):
web_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web_1  |   File "/usr/local/lib/python3.11/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 278, in delete_file
web_1  |     if self.storage.exists(prefixed_path):
web_1  |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web_1  |   File "/usr/local/lib/python3.11/site-packages/django/core/files/storage/filesystem.py", line 165, in exists
web_1  |     return os.path.lexists(self.path(name))
web_1  |                            ^^^^^^^^^^^^^^^
web_1  |   File "/usr/local/lib/python3.11/site-packages/django/contrib/staticfiles/storage.py", line 39, in path
web_1  |     raise ImproperlyConfigured(
web_1  | django.core.exceptions.ImproperlyConfigured: You're using the staticfiles app without having set the STATIC_ROOT setting to a filesystem path.
web_1  | Watching for file changes with StatReloader
web_1  | Performing system checks...
web_1  | 
web_1  | System check identified no issues (0 silenced).
web_1  | December 21, 2023 - 13:33:44
web_1  | Django version 4.2.3, using settings 'myproject.settings'
web_1  | Starting development server at http://0.0.0.0:8000/
web_1  | Quit the server with CONTROL-C.

```

**Comment by hseritt** [comment]
Done. and fixed.
